somaLabels = parseNml('R:\Anna\somaTracingRetina.nml');

filename = 'D:\sync\wholeCell\retina\bpc\isoForPaper\retinaSomas.hx';
fid = fopen(filename, 'w+');

for i=1:length(somaLabels)
    % Write code to create a 'create sphere' module
    fprintf(fid,[...
    'set hideNewModules 0\n' ...
    'create HxCreateSphere {CreateSphere' num2str(i,'%.3i') '}\n' ...
    'CreateSphere' num2str(i,'%.3i') ' setIconPosition 50 ' num2str(1500+50*i, '%i') '\n' ...
    'CreateSphere' num2str(i,'%.3i') ' fire\n' ...
    'CreateSphere' num2str(i,'%.3i') ' type setValue 0\n' ...
    'CreateSphere' num2str(i,'%.3i') ' radius setMinMax 0 3000\n' ...
    'CreateSphere' num2str(i,'%.3i') ' radius setButtons 0\n' ...
    'CreateSphere' num2str(i,'%.3i') ' radius setIncrement 0.666667\n' ...
    'CreateSphere' num2str(i,'%.3i') ' radius setValue 3000\n' ...
    'CreateSphere' num2str(i,'%.3i') ' radius setSubMinMax 0 3000\n' ...
    'CreateSphere' num2str(i,'%.3i') ' coords setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038\n' ...
    'CreateSphere' num2str(i,'%.3i') ' coords setValue 0 ' num2str(somaLabels{i}.nodes(1)*12, '%i') '\n' ...
    'CreateSphere' num2str(i,'%.3i') ' coords setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038\n' ...
    'CreateSphere' num2str(i,'%.3i') ' coords setValue 1 ' num2str(somaLabels{i}.nodes(2)*12, '%i') '\n' ...
    'CreateSphere' num2str(i,'%.3i') ' coords setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038\n' ...
    'CreateSphere' num2str(i,'%.3i') ' coords setValue 2 ' num2str(somaLabels{i}.nodes(3)*25, '%i') '\n' ...
    'CreateSphere' num2str(i,'%.3i') ' edgeLength setMinMax 1 1000\n' ...
    'CreateSphere' num2str(i,'%.3i') ' edgeLength setButtons 0\n' ...
    'CreateSphere' num2str(i,'%.3i') ' edgeLength setValue 300\n' ...
    'CreateSphere' num2str(i,'%.3i') ' edgeLength setSubMinMax 1 1000\n' ...
    'CreateSphere' num2str(i,'%.3i') ' nopPerUnit2 setMinMax 0.00001 20\n' ...
    'CreateSphere' num2str(i,'%.3i') ' nopPerUnit2 setButtons 0\n' ...
    'CreateSphere' num2str(i,'%.3i') ' nopPerUnit2 setValue 0.00001\n' ...
    'CreateSphere' num2str(i,'%.3i') ' nopPerUnit2 setSubMinMax 0.00001 20\n' ...
    'CreateSphere' num2str(i,'%.3i') ' fire\n' ...
    'CreateSphere' num2str(i,'%.3i') ' setViewerMask 16383\n' ...
    'CreateSphere' num2str(i,'%.3i') ' setPickable 1\n\n' ...
    ]);

    fprintf(fid,[...
    'set hideNewModules 0\n' ...
    '[ {CreateSphere' num2str(i,'%.3i') '} create\n' ...
    ' ] setLabel {SphereLat' num2str(i,'%.3i') '.surf}\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf setIconPosition 50 ' num2str(1525+50*i, '%i') '\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf master connect CreateSphere' num2str(i,'%.3i') '\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf fire\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf LevelOfDetail setMinMax -1 -1\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf LevelOfDetail setButtons 1\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf LevelOfDetail setIncrement 1\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf LevelOfDetail setValue -1\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf LevelOfDetail setSubMinMax -1 -1\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf fire\n' ...
    'SphereLat' num2str(i,'%.3i') '.surf setViewerMask 16383\n\n' ...
    ]);

    fprintf(fid,[...
    'set hideNewModules 0\n' ...
    'create HxDisplaySurface {SurfaceView' num2str(i,'%.3i') '}\n' ...
    'SurfaceView' num2str(i,'%.3i') ' setIconPosition 300 ' num2str(1525+50*i, '%i') '\n' ...
    'SurfaceView' num2str(i,'%.3i') ' data connect SphereLat' num2str(i,'%.3i') '.surf\n' ...
    'SurfaceView' num2str(i,'%.3i') ' colormap setDefaultColor 0.7 0.7 0.7\n' ...
    'SurfaceView' num2str(i,'%.3i') ' colormap setDefaultAlpha 1.000000\n' ...
    'SurfaceView' num2str(i,'%.3i') ' colormap setLocalRange 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' fire\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setValue 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' fire\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setSpecularLighting 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setTexture 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setAlphaMode 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setNormalBinding 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setSortingMode 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setLineWidth 0.000000\n' ...
    'SurfaceView' num2str(i,'%.3i') ' drawStyle setOutlineColor 0 0 0.2\n' ...
    'SurfaceView' num2str(i,'%.3i') ' textureWrap setIndex 0 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' cullingMode setValue 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' selectionMode setIndex 0 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' Patch setMinMax 0 48\n' ...
    'SurfaceView' num2str(i,'%.3i') ' Patch setButtons 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' Patch setIncrement 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' Patch setValue 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' Patch setSubMinMax 0 48\n' ...
    'SurfaceView' num2str(i,'%.3i') ' BoundaryId setIndex 0 -1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' materials setIndex 0 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' materials setIndex 1 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' colorMode setIndex 0 5\n' ...
    'SurfaceView' num2str(i,'%.3i') ' baseTrans setMinMax 0 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' baseTrans setButtons 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' baseTrans setIncrement 0.1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' baseTrans setValue 0.8\n' ...
    'SurfaceView' num2str(i,'%.3i') ' baseTrans setSubMinMax 0 1\n' ...
    'SurfaceView' num2str(i,'%.3i') ' VRMode setIndex 0 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' fire\n' ...
    'SurfaceView' num2str(i,'%.3i') ' hideBox 1\n' ...
    '{SurfaceView' num2str(i,'%.3i') '} selectTriangles zab HIJMONMBDBABAAAAAIMACABLNIDPONEMOBAHBEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPGGOLAAPBILMODN\n' ...
    'SurfaceView' num2str(i,'%.3i') ' fire\n' ...
    'SurfaceView' num2str(i,'%.3i') ' setViewerMask 16383\n' ...
    'SurfaceView' num2str(i,'%.3i') ' setShadowStyle 0\n' ...
    'SurfaceView' num2str(i,'%.3i') ' setPickable 1\n\n' ...
    ]);

end

fclose(fid);
